/**
 * Unified WASM Type Definitions
 *
 * Auto-generated by scripts/merge-wasm-types.js
 * DO NOT EDIT MANUALLY - Run 'node scripts/merge-wasm-types.js' to regenerate
 */

// ============================================================
// TASK-ENGINE MODULE
// ============================================================

/* tslint:disable */
/* eslint-disable */
/**
 * Task status enumeration
 */
export enum TaskStatus {
	/**
	 * Task is currently running
	 */
	Running = 0,
	/**
	 * Task is waiting for user interaction
	 */
	Interactive = 1,
	/**
	 * Task is in a resumable state
	 */
	Resumable = 2,
	/**
	 * Task is idle/waiting
	 */
	Idle = 3,
	/**
	 * Task is paused (waiting for subtask)
	 */
	Paused = 4,
	/**
	 * Task has been aborted
	 */
	Aborted = 5,
	/**
	 * Task has completed successfully
	 */
	Completed = 6,
}
/**
 * Main Task structure representing a single task instance
 */
export class Task {
	free(): void
	[Symbol.dispose](): void
	/**
	 * Create a new task instance
	 */
	constructor(task_mode: string, parent_task_id?: string | null)
	/**
	 * Start task execution
	 */
	start(initial_message: string): Promise<void>
	/**
	 * Pause task (for subtask spawning)
	 */
	pause(): Promise<void>
	/**
	 * Resume task (after subtask completion)
	 */
	resume(): Promise<void>
	/**
	 * Abort task execution
	 */
	abort(reason: string): Promise<void>
	/**
	 * Complete task
	 */
	complete(): Promise<void>
	/**
	 * Get task ID
	 */
	readonly task_id: string
	/**
	 * Get instance ID
	 */
	readonly instance_id: string
	/**
	 * Get current task mode
	 */
	readonly task_mode: string
	/**
	 * Check if task is paused
	 */
	readonly is_paused: boolean
	/**
	 * Check if task is aborted
	 */
	readonly is_aborted: boolean
	/**
	 * Get task status as string
	 */
	readonly status: string
}
export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module
export interface InitOutput {
	readonly memory: WebAssembly.Memory
	readonly __wbg_task_free: (a: number, b: number) => void
	readonly task_new: (a: number, b: number, c: number, d: number) => number
	readonly task_task_id: (a: number, b: number) => void
	readonly task_instance_id: (a: number, b: number) => void
	readonly task_task_mode: (a: number, b: number) => void
	readonly task_start: (a: number, b: number, c: number) => number
	readonly task_pause: (a: number) => number
	readonly task_resume: (a: number) => number
	readonly task_abort: (a: number, b: number, c: number) => number
	readonly task_complete: (a: number) => number
	readonly task_is_paused: (a: number) => number
	readonly task_is_aborted: (a: number) => number
	readonly task_status: (a: number, b: number) => void
	readonly __wbindgen_export_0: (a: number) => void
	readonly __wbindgen_export_1: (a: number, b: number) => number
	readonly __wbindgen_export_2: (a: number, b: number, c: number, d: number) => number
	readonly __wbindgen_export_3: WebAssembly.Table
	readonly __wbindgen_add_to_stack_pointer: (a: number) => number
	readonly __wbindgen_export_4: (a: number, b: number, c: number) => void
	readonly __wbindgen_export_5: (a: number, b: number, c: number) => void
	readonly __wbindgen_export_6: (a: number, b: number, c: number, d: number) => void
}
export type SyncInitInput = BufferSource | WebAssembly.Module
/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput
/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */

// ============================================================
// TOOLS MODULE
// ============================================================

/* tslint:disable */
/* eslint-disable */
/**
 * Create a new tool registry with all tools
 */
export function create_tool_registry(): any
/**
 * Create an empty tool registry
 */
export function create_empty_tool_registry(): any
/**
 * Check if a tool is available in the registry
 */
export function is_tool_available(registry_js: any, tool_name: string): boolean
/**
 * Get all available tools from the registry
 */
export function get_available_tools(registry_js: any): any
/**
 * Get tools in a specific group
 */
export function get_tools_in_group(registry_js: any, group: string): any
/**
 * Register a tool in the registry
 */
export function register_tool(registry_js: any, tool_name: string): any
/**
 * Unregister a tool from the registry
 */
export function unregister_tool(registry_js: any, tool_name: string): any
/**
 * Validate a tool in the registry
 */
export function validate_tool(registry_js: any, tool_name: string): boolean
/**
 * Enable all tools in a group
 */
export function enable_group(registry_js: any, group: string): any
/**
 * Disable all tools in a group (except always available)
 */
export function disable_group(registry_js: any, group: string): any
/**
 * Get tool count in the registry
 */
export function get_tool_count(registry_js: any): number
export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module
export interface InitOutput {
	readonly memory: WebAssembly.Memory
	readonly create_tool_registry: () => number
	readonly create_empty_tool_registry: () => number
	readonly is_tool_available: (a: number, b: number, c: number) => number
	readonly get_available_tools: (a: number) => number
	readonly get_tools_in_group: (a: number, b: number, c: number) => number
	readonly register_tool: (a: number, b: number, c: number) => number
	readonly unregister_tool: (a: number, b: number, c: number) => number
	readonly validate_tool: (a: number, b: number, c: number) => number
	readonly enable_group: (a: number, b: number, c: number) => number
	readonly disable_group: (a: number, b: number, c: number) => number
	readonly get_tool_count: (a: number) => number
	readonly __wbindgen_export_0: (a: number) => void
	readonly __wbindgen_export_1: (a: number, b: number) => number
	readonly __wbindgen_export_2: (a: number, b: number, c: number, d: number) => number
}
export type SyncInitInput = BufferSource | WebAssembly.Module
/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput
/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */

// ============================================================
// API-INTEGRATION MODULE
// ============================================================

/* tslint:disable */
/* eslint-disable */
/**
 * 初始化API Integration模块
 */
export function init(): void
/**
 * 获取模块版本
 */
export function getApiIntegrationVersion(): string
export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module
export interface InitOutput {
	readonly memory: WebAssembly.Memory
	readonly init: () => void
	readonly getApiIntegrationVersion: (a: number) => void
	readonly __wbindgen_add_to_stack_pointer: (a: number) => number
	readonly __wbindgen_export_0: (a: number, b: number, c: number) => void
	readonly __wbindgen_start: () => void
}
export type SyncInitInput = BufferSource | WebAssembly.Module
/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput
/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */

// ============================================================
// CONVERSATION MODULE
// ============================================================

/* tslint:disable */
/* eslint-disable */
/**
 * Create a new conversation manager
 */
export function create_conversation_manager(): any
/**
 * Add a message to the conversation
 */
export function add_message(manager_js: any, message_js: any): any
/**
 * Get all messages from the conversation
 */
export function get_messages(manager_js: any): any
/**
 * Get conversation statistics
 */
export function get_stats(manager_js: any): any
/**
 * Find a message by timestamp
 */
export function find_message_by_timestamp(manager_js: any, timestamp: bigint): any
/**
 * Clear all messages from the conversation
 */
export function clear_messages(manager_js: any): any
/**
 * Get messages since last summary
 */
export function get_messages_since_last_summary(messages_js: any): any
/**
 * Truncate conversation to a specific index
 */
export function truncate_conversation(manager_js: any, index: number): any
/**
 * Calculate how many messages to keep during condensing
 */
export function calculate_messages_to_keep(total_messages: number, context_usage_percent: number): number
export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module
export interface InitOutput {
	readonly memory: WebAssembly.Memory
	readonly create_conversation_manager: (a: number) => void
	readonly add_message: (a: number, b: number, c: number) => void
	readonly get_messages: (a: number, b: number) => void
	readonly get_stats: (a: number, b: number) => void
	readonly find_message_by_timestamp: (a: number, b: number, c: bigint) => void
	readonly clear_messages: (a: number, b: number) => void
	readonly get_messages_since_last_summary: (a: number, b: number) => void
	readonly truncate_conversation: (a: number, b: number, c: number) => void
	readonly calculate_messages_to_keep: (a: number, b: number) => number
	readonly __wbindgen_export_0: (a: number, b: number) => number
	readonly __wbindgen_export_1: (a: number, b: number, c: number, d: number) => number
	readonly __wbindgen_export_2: (a: number) => void
	readonly __wbindgen_add_to_stack_pointer: (a: number) => number
}
export type SyncInitInput = BufferSource | WebAssembly.Module
/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput
/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */

// ============================================================
// MEMORY MODULE
// ============================================================

/* tslint:disable */
/* eslint-disable */
/**
 * Utility: Calculate text similarity (Jaccard)
 */
export function calculateTextSimilarity(text1: string, text2: string): number
/**
 * Utility: Parse memory priority from string
 */
export function parseMemoryPriority(priority_str: string): any
/**
 * Utility: Parse memory type from string
 */
export function parseMemoryType(type_str: string): any
/**
 * Memory priority levels
 */
export enum MemoryPriority {
	/**
	 * Low priority - can be deleted
	 */
	Low = 0,
	/**
	 * Medium priority - can be compressed if necessary
	 */
	Medium = 1,
	/**
	 * High priority - should be kept
	 */
	High = 2,
	/**
	 * Critical - must never be lost
	 */
	Critical = 3,
}
/**
 * Memory type enumeration
 */
export enum MemoryType {
	/**
	 * User's explicit instruction
	 */
	UserInstruction = 0,
	/**
	 * Technical decision
	 */
	TechnicalDecision = 1,
	/**
	 * Configuration requirement
	 */
	Configuration = 2,
	/**
	 * Important error or issue
	 */
	ImportantError = 3,
	/**
	 * Project context
	 */
	ProjectContext = 4,
	/**
	 * Workflow pattern
	 */
	WorkflowPattern = 5,
}
/**
 * Memory System Manager (WASM Interface)
 */
export class MemoryManager {
	free(): void
	[Symbol.dispose](): void
	/**
	 * Create a new memory manager
	 */
	constructor(task_id: string, config: any)
	/**
	 * Extract memories from conversation messages
	 */
	extractMemories(messages: any, timestamp: number): any
	/**
	 * Get all memories
	 */
	getAllMemories(): any
	/**
	 * Get critical memories
	 */
	getCriticalMemories(): any
	/**
	 * Get memories by priority
	 */
	getMemoriesByPriority(priority: string): any
	/**
	 * Get memories by type
	 */
	getMemoriesByType(memory_type: string): any
	/**
	 * Record memory access
	 */
	recordMemoryAccess(memory_id: string, timestamp: number): void
	/**
	 * Generate memory summary for prompt
	 */
	generateMemorySummary(timestamp: number): string
	/**
	 * Apply memory aging mechanism
	 */
	applyMemoryAging(current_time: number): void
	/**
	 * Prune low priority memories
	 */
	pruneLowPriorityMemories(max_count: number, current_time: number): void
	/**
	 * Get memory statistics
	 */
	getMemoryStats(current_time: number): any
	/**
	 * Serialize to JSON string
	 */
	serialize(): string
	/**
	 * Deserialize from JSON string
	 */
	static deserialize(data: string): MemoryManager
}
export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module
export interface InitOutput {
	readonly memory: WebAssembly.Memory
	readonly __wbg_memorymanager_free: (a: number, b: number) => void
	readonly memorymanager_new: (a: number, b: number, c: number, d: number) => void
	readonly memorymanager_extractMemories: (a: number, b: number, c: number, d: number) => void
	readonly memorymanager_getAllMemories: (a: number, b: number) => void
	readonly memorymanager_getCriticalMemories: (a: number, b: number) => void
	readonly memorymanager_getMemoriesByPriority: (a: number, b: number, c: number, d: number) => void
	readonly memorymanager_getMemoriesByType: (a: number, b: number, c: number, d: number) => void
	readonly memorymanager_recordMemoryAccess: (a: number, b: number, c: number, d: number) => void
	readonly memorymanager_generateMemorySummary: (a: number, b: number, c: number) => void
	readonly memorymanager_applyMemoryAging: (a: number, b: number) => void
	readonly memorymanager_pruneLowPriorityMemories: (a: number, b: number, c: number) => void
	readonly memorymanager_getMemoryStats: (a: number, b: number, c: number) => void
	readonly memorymanager_serialize: (a: number, b: number) => void
	readonly memorymanager_deserialize: (a: number, b: number, c: number) => void
	readonly calculateTextSimilarity: (a: number, b: number, c: number, d: number) => number
	readonly parseMemoryPriority: (a: number, b: number, c: number) => void
	readonly parseMemoryType: (a: number, b: number, c: number) => void
	readonly __wbindgen_export_0: (a: number) => void
	readonly __wbindgen_export_1: (a: number, b: number) => number
	readonly __wbindgen_export_2: (a: number, b: number, c: number, d: number) => number
	readonly __wbindgen_add_to_stack_pointer: (a: number) => number
	readonly __wbindgen_export_3: (a: number, b: number, c: number) => void
}
export type SyncInitInput = BufferSource | WebAssembly.Module
/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput
/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */

// ============================================================
// INITIALIZATION FUNCTIONS
// ============================================================

export function initTaskEngine(): Promise<void>
export function initTools(): Promise<void>
export function initApiIntegration(): Promise<void>
export function initConversation(): Promise<void>
export function initMemory(): Promise<void>
export function initAll(): Promise<void>
