/**
 * WASM Loader for Roo-Code
 *
 * This module handles loading and initialization of the Rust WASM module,
 * injecting Host Interface implementations, and providing a clean API
 * for TypeScript code to interact with Rust core logic.
 */

import { getHostInterface } from "./HostInterface"
import * as path from "path"
import * as fs from "fs/promises"

// ============================================================================
// Type Definitions
// ============================================================================

/**
 * WASM module interface generated by wasm-bindgen
 */
export interface RooWasmModule {
	initialize(): string
	create_task(title: string, description: string): Promise<string>
	get_task_state(taskId: string): Promise<string>
	update_task_state(taskId: string, state: string): Promise<void>
	add_memory(memoryType: string, content: string, priority: string): Promise<string>
	search_memory(query: string, limit: number): Promise<string>
	// More methods will be added as Rust implementation grows
}

/**
 * WASM initialization options
 */
export interface WasmInitOptions {
	wasmPath?: string
	enableLogging?: boolean
	maxMemoryMB?: number
}

// ============================================================================
// WASM Loader Class
// ============================================================================

export class WasmLoader {
	private wasmModule: RooWasmModule | null = null
	private isInitialized: boolean = false
	private initPromise: Promise<void> | null = null

	/**
	 * Initialize WASM module
	 * @param options Initialization options
	 */
	async initialize(options: WasmInitOptions = {}): Promise<void> {
		// Prevent multiple initializations
		if (this.isInitialized) {
			return
		}

		if (this.initPromise) {
			return this.initPromise
		}

		this.initPromise = this._doInitialize(options)
		await this.initPromise
	}

	/**
	 * Internal initialization implementation
	 */
	private async _doInitialize(options: WasmInitOptions): Promise<void> {
		try {
			const startTime = Date.now()

			// Resolve WASM file path
			const wasmPath = options.wasmPath || this.getDefaultWasmPath()

			if (options.enableLogging) {
				console.log(`[WasmLoader] Loading WASM from: ${wasmPath}`)
			}

			// Check if WASM file exists
			try {
				await fs.access(wasmPath)
			} catch {
				throw new Error(
					`WASM file not found: ${wasmPath}\n` +
						`Please build the Rust project first:\n` +
						`  cd rust-wasm && wasm-pack build --target web`,
				)
			}

			// Load WASM binary
			const wasmBinary = await fs.readFile(wasmPath)

			if (options.enableLogging) {
				console.log(`[WasmLoader] WASM file size: ${wasmBinary.length} bytes`)
			}

			// Import wasm-bindgen generated JS
			const wasmBindgenPath = path.join(path.dirname(wasmPath), "roo_core.js")
			const wasmBindgen = await import(wasmBindgenPath)

			// Initialize with imported binary and inject Host Interface
			await wasmBindgen.default(wasmBinary)

			// Inject Host Interface functions
			this.injectHostInterface(wasmBindgen)

			// Store module reference
			this.wasmModule = wasmBindgen as unknown as RooWasmModule

			// Initialize the Rust module
			const version = this.wasmModule.initialize()

			this.isInitialized = true

			const elapsed = Date.now() - startTime

			if (options.enableLogging) {
				console.log(`[WasmLoader] Initialized ${version} in ${elapsed}ms`)
			}
		} catch (error) {
			this.isInitialized = false
			this.initPromise = null
			throw new Error(`Failed to initialize WASM: ${error}`)
		}
	}

	/**
	 * Inject Host Interface implementations into WASM module
	 */
	private injectHostInterface(wasmBindgen: any): void {
		const hostInterface = getHostInterface()

		// Create global __HOST_INTERFACE__ object for Rust to call
		;(globalThis as any).__HOST_INTERFACE__ = {
			// File System
			readFile: (path: string) => hostInterface.readFile(path),
			writeFile: (path: string, content: string) => hostInterface.writeFile(path, content),
			fileExists: (path: string) => hostInterface.fileExists(path),
			listDir: (path: string) => hostInterface.listDir(path),
			createDir: (path: string) => hostInterface.createDir(path),
			deleteFile: (path: string) => hostInterface.deleteFile(path),
			getFileMetadata: (path: string) => hostInterface.getFileMetadata(path),

			// Terminal
			executeCommand: (cmd: string, cwd?: string) => hostInterface.executeCommand(cmd, cwd),
			getTerminalOutput: (pid: string) => hostInterface.getTerminalOutput(pid),
			killProcess: (pid: string) => hostInterface.killProcess(pid),

			// UI
			showNotification: (msg: string, level: string) => hostInterface.showNotification(msg, level),
			askApproval: (msg: string, options: string[]) => hostInterface.askApproval(msg, options),
			askInput: (prompt: string, defaultValue?: string) => hostInterface.askInput(prompt, defaultValue),
			showError: (msg: string) => hostInterface.showError(msg),

			// Network
			httpRequest: (url: string, config: any) => hostInterface.httpRequest(url, config),
			httpStream: (url: string, config: any) => hostInterface.httpStream(url, config),

			// Config
			getConfig: (key: string) => hostInterface.getConfig(key),
			setConfig: (key: string, value: string) => hostInterface.setConfig(key, value),

			// Vector DB
			vectorSearch: (params: any) => hostInterface.vectorSearch(params),
			vectorInsert: (params: any) => hostInterface.vectorInsert(params),
		}
	}

	/**
	 * Get default WASM file path
	 */
	private getDefaultWasmPath(): string {
		// In production, WASM will be bundled with extension
		// For development, use the build output
		const wasmFileName = "roo_core_bg.wasm"

		// Try multiple possible locations
		const possiblePaths = [
			// Development build location
			path.join(__dirname, "../../../rust-wasm/pkg", wasmFileName),
			// Production bundle location (will be set during packaging)
			path.join(__dirname, "../../wasm", wasmFileName),
			// Alternative location
			path.join(__dirname, "../wasm", wasmFileName),
		]

		// Return first path (will check existence during initialization)
		return possiblePaths[0]
	}

	/**
	 * Get WASM module (must be initialized first)
	 */
	getModule(): RooWasmModule {
		if (!this.isInitialized || !this.wasmModule) {
			throw new Error("WASM module not initialized. Call initialize() first.")
		}
		return this.wasmModule
	}

	/**
	 * Check if WASM is initialized
	 */
	isReady(): boolean {
		return this.isInitialized
	}

	/**
	 * Cleanup WASM resources
	 */
	async cleanup(): Promise<void> {
		if (this.wasmModule) {
			// Cleanup logic if needed
			this.wasmModule = null
		}
		this.isInitialized = false
		this.initPromise = null

		// Cleanup Host Interface global
		delete (globalThis as any).__HOST_INTERFACE__
	}
}

// ============================================================================
// Singleton Instance
// ============================================================================

let wasmLoaderInstance: WasmLoader | null = null

/**
 * Get singleton WASM loader instance
 */
export function getWasmLoader(): WasmLoader {
	if (!wasmLoaderInstance) {
		wasmLoaderInstance = new WasmLoader()
	}
	return wasmLoaderInstance
}

/**
 * Initialize WASM (convenience function)
 */
export async function initializeWasm(options?: WasmInitOptions): Promise<RooWasmModule> {
	const loader = getWasmLoader()
	await loader.initialize(options)
	return loader.getModule()
}

/**
 * Get WASM module (must be initialized first)
 */
export function getWasmModule(): RooWasmModule {
	const loader = getWasmLoader()
	return loader.getModule()
}
